[package]
name = "fformat_utils"
version = "0.2.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["dict", "serde"]
dict = ["scc", "thiserror", "ahash"]

[dependencies]
crc32fast = "1"
thiserror = { version = "1", optional = true }
scc = { version = "2", optional = true }
ahash = { version = "0.8", optional = true }
serde = { version = "1", optional = true }
bytemuck = { version = "1", optional = true }
